baseURL = "https://poetic-mochi-5f1707.netlify.app"
languageCode = "en-us"
paginate = 6
summarylength = 10
title = "Gypsy Lulu | Travel Blog"
theme = "blogge-hugo-theme"

[menu]
  [[menu.main]]
    name = "Home"
    url= ""
    weight= 1
  [[menu.main]]
    name = "Food"
    url= "food"
    weight= 2
  [[menu.main]]
    name = "How to Articles"
    url= "how_to"
    weight= 3
  [[menu.main]]
    name = "Places"
    url= "places"
    weight= 4
  [[menu.main]]
    name = "About"
    url= "about"
    weight= 5
  [[menu.main]]
    name = "Contact"
    url= "contact"
    weight= 6


[params]
  summarylength = 80
  logo = "images/logo.svg"
  author = "Luana Nicosia & Matthew Henderson"
  authorThumb = "images/matt-and-lulu.png"
  authorAddress = "Lorem 142 Str., 2352, Ipsum, State, USA"
  authorPhone = "+33-257634 534"
  instaUsername = "mary_astor"
  facebookUsername = "mary_astor"
  twitterUsername = "mary_astor"
  linkedinUsername = "mary_astor"
  blogTitle = "Articles"
  blogSubTitle = "View the latest news on Blogger"
  trendingBlogIcon = "images/blog/icon.svg"
  # Replace the third party URL/API with yours
  # We're using formspree.io for form handling, paste your formspree url below
  fabformURL  = "9AJk8ro"
  googleMapAPI = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"

[taxonomies]
  tag = "tags"
